### ISSUE TITLE
AdminOrders page very slow after upgrade

### ISSUE THREAD

**Issue by jefkeijers** [mollie/PrestaShop#203]
Since updating to the latest Mollie module (v4.0.7), I noticed that the back office AdminOrders page loaded very slow. 

After investigation I found that the query for the AdminOrders page was slightly changed. Running the full query took over 4000ms. After removal of the extra LEFT JOIN it runs only 200ms (see code below)

`' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference`';
`
Best to add an extra index on the SQL script?

Environment
* PrestaShop version: 1.7.4.2
* Mollie module version: 4.0.7

**Comment by jefkeijers** [comment]
After adding an index to the order_reference column of table ps_mollie_payments, the problem is solved. Query time reduced to 220ms.

**Comment by SimonasB88** [comment]
Hey @jefkeijers thanks for your insghts, just letting you know, that we are on to this case, doing some testing.
I will update you when I will get the latest from our dev team!

Best Regards.

**Comment by SimonasB88** [comment]
Hey,
The improvement is included into 4.0.8. Thanks for your insight!
Best Regards.

**Comment by 30knees** [comment]
I'd like to pick up on this as I still have the same issue in 4.1.1. with the latest thirtybees/Prestashop 1.6. Has the fix in 4.0.8 been reverted or is this another issue that only affects PS 1.6?

**Comment by Saimis777** [comment]
Hello @30knees and thank you for your message.

Would you be able to raise a new issue with steps about the issue, how to locate it, and how to reproduce it, please?

Thank you.

Best regards,
Invertus Support team
