### ISSUE TITLE
Firstname, Lastname and e-mail $template vars not coming through in order_conf and new_order mail

### ISSUE THREAD

**Issue by imagicuus** [mollie/PrestaShop#247]
### Expected behavior
When the order_conf and new_order mails are send all template vars should show up.

### Actual behavior
When using Mollie plugin with both emails on "send when payed" the template vars {firstname} {lastname} and {email} are not showing up in the e-mail that is send. Rest of the e-mail looks fine.

### Steps to reproduce the behavior
Both e-mails on "send when payed", I'm also working on a multistore environment

### Environment
* PrestaShop version: 1.7.6.9 
* Mollie module version: 4.1.0
* PHP version: 7.2

**Comment by SimonasB88** [comment]
Hey @imagicuus thanks for your message, I can assure we have backloged this case.
Will be back with the news after we reproduce on out test environments.

Best Regards.

**Comment by Xesau** [comment]
Can confirm this issue.

**Comment by Maikel726** [comment]
Hi,

I've had the same issue after upgrading to Prestashop version 1.7.6.9, the issue was fixed after i changed the e-mail settings from send as HTML to send as text and change it back. You can find these settings in: Backoffice - > advanced settings - > E-mail.

Hopefully does this fix the issue for you too

**Comment by SimonasB88** [comment]
Hey guys, thanks for your insights! 

Currently the dev team is on this case. We will update you after the investigation.

Best Regards.

**Comment by SimonasB88** [comment]
Hello once again @imagicuus , we couldn't be able to reproduce the issue on our test environments,
could you please provide us:

URL back office:
login back office:
password back office:

FTP host:
FTP login:
FTP password:
FTP port:

Send everything to support@invertus.eu.

Best Regards.

**Comment by imagicuus** [comment]
@SimonasB88 hm, I guess I will have to create a separate environment for this. Have you tested it with a multistore setup?

I've tried the solution of @Maikel726 but this didn't seem to work.

**Comment by SimonasB88** [comment]
@imagicuus 
We have tested on 1.7.6.9 PS version, Mollie 4.1.0 and ps_emailalerts. Configured Mollie to send emails on paid status. Did not manage reproduce issue still.
The only best way I guess would be to check on your environment, to do quick testing, and let you know the outcome. 

We are doing supporting development for many merchants, so you could kindly provide the credentials as well and we could help you as well.

Best Regards.

**Comment by Saimis777** [comment]
Hello @imagicuus, hope you're having a good day. Have you managed to provide your details to our support team for further investigation on your environment? And does the issue still persist? 

We are going to close this issue for now due to inactivity, but if anything, let us know, we are here to help!

You can always contact us via our email - support@invertus.eu

Best regards,
Invertus Support team
