### ISSUE TITLE
Not possible to pay in SGD.

### ISSUE THREAD

**Issue by BricksDirect** [mollie/PrestaShop#294]
### Expected behavior
Payments should be possible when SGD selected.
Check this link:
https://docs.mollie.com/payments/multicurrency

### Actual behavior
Mollie payment option not shown when SGD selected. 

### Steps to reproduce the behavior
Try to pay with SGD.

### Environment
* PrestaShop version: 1.7.6.9
* Mollie module version: 4.2.2
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hey @BricksDirect Thank you for reporting the issue!

We will check this further, and I will let you know if more information is needed!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @BricksDirect ,

Just wanted to inform you that we've found the issue, currently we've implemented a fix, and are testing it, and I will keep you updated regarding this matter!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Hello Invertus team,

That's great!
I will wait on your solution.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
Hello,

Thank you for your patience, could you also clarify if you click on refresh currency values button in Mollie BO, does it help?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Hello,

No, it doesn't make a difference.
It is still not possible to pay in SGD.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
Hey @BricksDirect ,

Just to double check, you've reset the currency values here, correct?
![image](https://user-images.githubusercontent.com/75423142/109297362-89c8b300-783a-11eb-9f72-c8aa31db9c74.png)

Cleared your cache afterwords, and it still did not help, right?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Hello,

Yes I have already refreshed by clicking on that button.
The mollie payment option is still not shown when SGD selected.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
@BricksDirect ,

And could you clarify if there are no country/currency restrictions in this section here?
![image](https://user-images.githubusercontent.com/75423142/109498855-bd0a7c80-7a9c-11eb-8af5-e172661149cd.png)
![image](https://user-images.githubusercontent.com/75423142/109498863-c267c700-7a9c-11eb-9546-c86471d408b6.png)

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Hello,

I already checked that.
There are no restrictions in these settings.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
@BricksDirect ,

In that case, could you maybe send your back office/FTP credentials to - support@invertus.eu for further investigation?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

At the moment we are testing the implemented fix for the issue, and included it in the 4.2.3 release which is coming out really soon, I will notify you once it's released!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Dear Invertus team,

That's great.
Thank you.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
Hello @BricksDirect ,

The latest version 4.2.3 was just released with the fix included! You can download it here - https://github.com/mollie/Prestashop/releases

Let us know once you've installed and tested it, we would love to receive further feedback regarding the module!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @BricksDirect ,

Did you have time to install the 4.2.3 version and give it a try? Is everything working as it should? Do you need further assistance?

Let us know!

--
Best regards,
Invertus Support team

**Comment by BricksDirect** [comment]
Hello Invertus Support team,

It works fine now.
The bug has been solved.
Thank you for your assistance.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment]
Thank you for the clarification @BricksDirect ,

Closing the issue now, have a nice day!

--
Best regards,
Invertus Support team
