### ISSUE TITLE
" Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart "

### ISSUE THREAD

**Issue by vrijndesteede** [mollie/PrestaShop#32]
Hi All.
 
I am using Prestashop 1.6.1.10 and am now opening my second store.
 
The first store never had any issues with returning the cart status. But the second now doesn't get some things work. I am using Mollie payment module. ( https://github.com/mollie/Prestashop ). The shop is NOT in maintenance mode during the tests. 
 
- Order is correctly handled -> Payment is accepted in the order screen
- Customer gets screen with 'no final payment status' 
- Customer gets NO e-mail of confirmation.
- SSL is enabled in my first store, I tried to solve this issue in both SSL and without SSL. 
 
I already synchronized all settings of the two webshops, so I do not really know what else can be a solution. 
 
The error in the log is the following:
`" Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart "
` 
How to solve the issue so the customer gets a confirmation, and the user sees the confirmation screen.
 
Any help is very welcome!!
 
Thank you in advance.

**Comment by freskimo** [comment]
+1

**Comment by evgenij-sobolev** [comment]
+1
The same error in System log
![2017-03-28 17 57 01](https://cloud.githubusercontent.com/assets/20418648/24412039/132f4528-13e0-11e7-9510-7c3ce87cd00c.png)

**Comment by joriscrozier** [comment]
Same here, biggest problem is : no payment confirmation are sent by email for customers ...

**Comment by mkzcore** [comment]
Same here, page loading forever (order in BO but no confirmation screen for customer).

**Comment by mkzcore** [comment]
In my case it is related to the mail settings. I was using google smtp, which caused issues (don't know why). For a test i set in PS BO in menu "Advanced Parameters > E-mail" the mail settings to "never send emails". Did a test order and confirmation page was there in about 3 seconds. Then I set it to "Use PHP mail function" and since then the issues with confirmation page not loading / mails not sent has been solved.

I keep an eye out if i still get this ordercontroller error.

**Comment by andreas-waldherr** [comment]
Same Problem here! Happens on my Prestashop (no confirmation screen) when payment was done with SOFORTÜBERWEISUNG. Does always work with stripe payment service! And I can avoid this problem by clearing the Client Browser Cache! 

Using PHP Mailer does also as workaround - but I don’t like to use it because PS runs on hosting provider and therefore I am afraid that mails are caught by spam and/or blacklist filter...

I will also open an Prestashop Case tomorrow.

**Comment by mpragliola** [comment]
Same problem here. The faiiling point seems:

`if (Validate::isLoadedObject($this->context->cart) && $this->context->cart->OrderExists() == false) {`

I am working on an **absolutely untouched** installation.

**Comment by Trendweb** [comment]
As Mollie returns to the shop, a brand new cart number should be set and updated. The frontcontroller checks if an order has already been placed with the cart number as it returns to prestashop. The cart number is still the same because (upon return) no new cart number has been set yet. And therefore, it places a log entry saying the the current cart is already related to an order in the database.

So just before mollie sets the return.tpl template, a new cart number should be created and updated. We have tested this in a new beta version and the abovementioned solves the problem. It will be implemented in the next Mollie update.

We will close this Issue as soon as the update is released.

Regards

**Comment by evgenij-sobolev** [comment]
Great news!
We are waiting for the update!

**Comment by Dbl0207** [comment]
Is this issue solved? I have the issue in 1.6.1.6 for one client and the other client in 1.7 is running fine absolutely. Can some assist ?

**Comment by Trendweb** [comment]
Hi @Dbl0207 yes this issue is solved and the update will be placed on Github very soon. We are currently cleaning up the code and doing the last checks. Could you please contact us at info@trendweb.nl? We can provide you with a working version with the fix for this problem.

Kind Regards

**Comment by eltemucano** [comment]
Same problem but with 1.7.2.4 ... not always but seems to be a random error.  
I will have to disable emails to clients while I find a way to correct this error or bug. Thankful to advise any update for this matter.

**Comment by Trendweb** [comment]
Hi @eltemucano,

We are Mollie's Prestashop partner. Could you contact us at info@trendweb.nl and please let us know why you have to disable the e-mails? We will gladly help you out on this matter.

Kind Regards

**Comment by eltemucano** [comment]
Hello

I reviewed among the proposals that could avoid that problem and in these
moments I am trying to make my sales and send the mails manually. The issue
is that it does not appear continuously and the message "FrontController"
itself, with the transaction approved or not always registered. This could
result in my store not functioning properly and losing customers. I spoke
with the developer of the plugin for payment with a credit card (TRANSBANK
CHILE) and he told me that he does not register problems of that type for
prestashop. In summary, I should wait for some update to solve this.

Greetings and best regards,
Christian - "Eltemucano".

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-28 6:50 GMT-03:00 Trendweb <notifications@github.com>:

**Comment by Trendweb** [comment]
Hi @eltemucano // Christian,

Thank you for your reply. The reason i asked you to contact us via e-mail, is the fact that there are several different causes for this error. We encountered that a 1 page checkout module was causing problems with the Mollie module and also a different module // override causing this problem. So if you have a simular problem, the update might not suffice. So therefore, please contact us so we can get to the root of the problem and determine where exactly this is comming from.

Kind Regards

**Comment by snowycatsoftware** [comment]
This issue has been solved in the latest version of the Mollie module (2.0.0). Therefore we are closing this issue.

Kind Regards
